### ISSUE TITLE
Which kernel is used to develop these patches?

### ISSUE THREAD

**Issue by mikhailnov** [kernins/linux-chwhi12#1]
Hello, can you please specify, which kernel version is used to build with these patches? And which kernel are you using on Chuwi Hi12 and what works and does not. Thank you.

**Comment by kernins** [comment]
The code was developed on late 4.12 - 4.13-rc. The latest I built and my current one is probably 4.13.2, if memory serves me.

Sound is fully working, except for PM issues reported in relevant kernel bug. Noone seem to be interested in them and me too have no time for this atm. Also pls note, I'm using pure ALSA and don't care about PA, it may have its own issues I don't know about. After fresh install you have to apply UCM from this repo with `alsa-ucm` tool or setup everything manually with series of `amixer` commands.

Touchscreen is fully working, and so does WiFi & BT, however the latter I've only tested once. 
Accelerometer should also work. 

SD card doesn't work, and there are some issues with GPU PM/backlight ctl.
Have had no time to properly report or dig into this yet.

**Comment by mikhailnov** [comment]
Thanks for the answer.
https://github.com/dsd/linux/commit/75dd23faa709c719bf61ab92593e7ece68b3a53d "Audio is working over suspend/resume without this" Will not it help with audio PM?

Is it enough to put alsa configs from your repo to propper directories?

**Comment by mikhailnov** [comment]
WOW! I put your sources on top of linux kernel 4.13.0-12 from ubuntu and now BOTH HEADPHONEs and SPEAKERS work!
Pulseaudio does work (without /etc/asound.conf)

How can we upstream your (or whose?) changes to the upstream linux kernel, where the sound works only via headphones, not speakers? I tried 4.14 daily build 05-10-2017

**Comment by mikhailnov** [comment]
And what about upstreaming UCM configs for alsa?

**Comment by kernins** [comment]
>Will not it help with audio PM?

Mainline version has already no pm-ops callbacks.
DAPM should be responsible for PM.

>How can we upstream your (or whose?) changes

ES8316 changes are definitely not ready for upstreaming. It is just some quick code I wrote to just get it working. Controlling analog switch (which could pretty much be machine specific) from codec driver context is not exactly a good idea, it's perfectly fine as a temporary solution for Hi12 and similar tablets, but definitely not for mainline

Goodix code however is fine I think, just need to find the time to clean it up

**Comment by mikhailnov** [comment]
А у вас микрофон работает на чистой ALSA? У меня с вашим драйвером в PulseAudio только произвольные шумы, а вот на апстримных ядрях, последнее которое проверял - 4.15 rc7, сейчас работают наушники и микрофон с Pulseaudio, но динамики не работают. Сделал диффы кода, вы почти никакой апстримный код не удаляли, ничего больше не понял, только вижу дергания незадокументированных GPIO.

**Comment by mikhailnov** [comment]
А вот на счет тачскрина. Просто так он на апстримных ядрах не работает, но внезапно заработал на LiveCD ALT Linux и на 4.9, и на 4.13 (http://altlinux.org/Starterkits, http://basealt.ru)! Подробнее здесь: https://vk.com/wall-667081_26097
Нет идей, почему так произошло и как заставить заработать на апстримном драйвере вне LiveCD? 
На других дистрибутивах в LiveCD тоже не работает. Добавил goodix в initrd на Альте (/etc/initrd.mk, https://www.altlinux.org/Make-initrd), бесполезно.

**Comment by mikhailnov** [comment]
вот здесь другие устройства с такой же материнской платой, все 5-6 проб с Hampoo P02BD6_HI-122LP - мои. Но остальные тоже имеют приставку HI-122LP , а модель планшета - Chuwi Hi12, скорее всего, это этот же планшет в других ревизиях
https://linux-hardware.org/index.php?id=board:hampoo-cherry-trail-cr-hampoo-reserve
Может быть, пригодиться.

**Comment by kernins** [comment]
>А у вас микрофон работает на чистой ALSA

Да, оба, встройка и гарнитура. С PA не тестил - не юзаю.
Кто-то вроде отзывался, что на PA тоже все ок, но это могло касаться только работы динамиков.

>дергания незадокументированных GPIO

Только это и добавлено, гпио управляет аналоговым свитчем, через который подключены динамики.
Наушники и оба микрофона работали изначально, после соответствующей настройки алсы.


Тач на Hi12 будет нормально работать только с патченым драйвером, учитывающим инверсию гпио, заведенного на ~RST чипа. Ну если, конечно, в новых ревизиях это не пофиксили на уровне биоса.

Без этого reset-sequence получается некорректной, но, тем не менее, при определенном стечении обстоятельств из 2 последовательных, но напрямую несвязанных, серий дерганья релевантных гпио может сложиться одна корректная резет-последовательность (на стыке этих серий). Так мне удавалось завести тач на апстримном драйвере простой перезагрузкой драйвера (rmmod && insmod). Если есть желание разобраться, смотрите даташиты, там есть все последовательности с таймингами, и сравнивайте с кодом драйвера.

Соответственно, фикс тача сводится к добавлению условной инверсии на линии ~rst, в моей версии он активируется по dmi-матчу на материнку "Hampoo" && "Cherry Trail CR". Остальные изменения по гудиксу в этой репе - это минорный рефакторинг и добавление поддержки runtime_pm, к фиксу прямого отношения не имеют.

**Comment by mikhailnov** [comment]
А можете сделать пробу оборудования https://github.com/linuxhw/hw-probe со своего планшета, чтобы сравнить железо?
